# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: build TourGuide
      run: |- 
           cd TourGuide
           ./gradlew compileJava
 
  test:

    runs-on: ubuntu-latest
    needs: compile
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: test TourGuide
      run: |- 
           cd TourGuide
           ./gradlew check
           ls -l .
           ls -l build
    - name: Upload tests reports
      uses: actions/upload-artifact@v3.1.3
      with:
    # Artifact name
         name: tourGuideTestReports
         path: TourGuide/build/jacocoHtml
    

  package:
    
    runs-on: ubuntu-latest
    needs: [compile, test]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: build TourGuide
      run: |- 
           cd TourGuide
           ./gradlew assemble

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
    # Artifact name
         name: tourGuideArtefacts
         path: TourGuide/build/libs/tourGuide-*.jar
       
    
